"use client"
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { useState } from "react";
import { CartProvider, useCart } from "react-use-cart";


const metadata = {
  title: "eastern-zaika",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [metaData, setMetaData] = useState(null);
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body
        className={`antialiased  bg-slate-900`}
      >
        <CartProvider>
          <Navbar />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
