import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Eastern-Zaika",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body
        className={`antialiased  bg-slate-900`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
